version: '3'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: on-failure
    command: --storage.tsdb.retention=15d
    command: --config.file=/etc/prometheus/prometheus.yml
    network_mode: "host"
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/prometheus/alert.rules:/etc/prometheus/alert.rules
      - /data:/prom/prometheus/data
#    environment:
